#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/pdx235

PRODUCT_COPY_FILES += \
    vendor/sony/pdx235/proprietary/vendor/etc/acdbdata/Sony_zambezi_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_zambezi_Bluetooth_cal.acdb \
    vendor/sony/pdx235/proprietary/vendor/etc/acdbdata/Sony_zambezi_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_zambezi_General_cal.acdb \
    vendor/sony/pdx235/proprietary/vendor/etc/acdbdata/Sony_zambezi_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_zambezi_Global_cal.acdb \
    vendor/sony/pdx235/proprietary/vendor/etc/acdbdata/Sony_zambezi_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_zambezi_Handset_cal.acdb \
    vendor/sony/pdx235/proprietary/vendor/etc/acdbdata/Sony_zambezi_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_zambezi_Hdmi_cal.acdb \
    vendor/sony/pdx235/proprietary/vendor/etc/acdbdata/Sony_zambezi_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_zambezi_Headset_cal.acdb \
    vendor/sony/pdx235/proprietary/vendor/etc/acdbdata/Sony_zambezi_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Sony_zambezi_Speaker_cal.acdb \
    vendor/sony/pdx235/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/sony/pdx235/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/sony/pdx235/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/sony/pdx235/proprietary/vendor/etc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_RF.conf \
    vendor/sony/pdx235/proprietary/vendor/etc/qdcm_calib_data_samsung_amoled_fhd_cmd_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_samsung_amoled_fhd_cmd_dsi_panel.xml \
    vendor/sony/pdx235/proprietary/vendor/etc/sensors/config/strait_qrd_af6133e_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_qrd_af6133e_0.json \
    vendor/sony/pdx235/proprietary/vendor/etc/sensors/config/strait_qrd_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/strait_qrd_mmc56x3x_0.json \
    vendor/sony/pdx235/proprietary/vendor/etc/wifi/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.bin \
    vendor/sony/pdx235/proprietary/vendor/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_acf.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.sensormodule.lce_hi847.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.lce_hi847.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.sensormodule.le_hi846_back.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.le_hi846_back.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.sensormodule.le_hi846_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.le_hi846_front.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.sensormodule.qtech_imx582.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qtech_imx582.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg0.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg0.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg1.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg2.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.tuned.blair_lce_hi847.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.blair_lce_hi847.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.tuned.blair_qtech_imx582.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.blair_qtech_imx582.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.tuned.le_hi846_back.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.le_hi846_back.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/com.qti.tuned.le_hi846_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.le_hi846_front.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/dualCaliParams_wt.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/dualCaliParams_wt.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/dualCaliParams_wu.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/dualCaliParams_wu.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/sony/pdx235/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    android.hardware.camera.provider@2.6-legacy \
    com.qti.eeprom.hi846_back_eeprom \
    com.qti.eeprom.hi846_front \
    com.qti.eeprom.truly_cmb433 \
    com.qti.flash.lm3644 \
    com.qti.sensor.hi846_back \
    com.qti.sensor.hi846_front \
    com.qti.sensor.hi847 \
    com.qti.sensor.imx582 \
    com.arcsoft.node.hdr \
    com.arcsoft.node.hdsr \
    com.arcsoft.node.llhdr \
    com.arcsoft.node.lls \
    com.arcsoft.node.mfsr \
    com.arcsoft.node.singlecamsupernight \
    com.arcsoft.node.smooth_transition \
    com.mms.node.bgstore \
    com.morpho.node.moviesolid \
    com.morpho.node.singlebokeh \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.asaisd \
    com.qti.node.ascd \
    com.qti.node.asfl \
    com.qti.node.asot \
    com.qti.node.assfprocess \
    com.qti.node.capturebokeh \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.realtimebokeh \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libdepthmapwrapper_secure \
    com.arcsoft.feature2.supernight \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.cedros \
    com.qti.feature2.gs.kamorta \
    com.qti.feature2.gs.kodiak \
    com.qti.feature2.gs.mannar \
    com.qti.feature2.gs.sdm865 \
    com.qti.feature2.gs.sm8350 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.settings.kamorta \
    com.qti.settings.kodiak \
    com.qti.settings.mannar \
    com.qti.settings.sdm865 \
    com.qti.settings.sm8350 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom \
    com.qti.chi.override \
    fingerprint.default \
    libarcimageprocess \
    libarcsoft_aiscenedetection \
    libarcsoft_antishaking \
    libarcsoft_beautyshot \
    libarcsoft_bokehplus_image \
    libarcsoft_bokehplus_video \
    libarcsoft_conditiondetection \
    libarcsoft_distortion_correction \
    libarcsoft_facialrestoration \
    libarcsoft_hdsuperresolution \
    libarcsoft_high_dynamic_range_v5 \
    libarcsoft_low_light_hdr \
    libarcsoft_low_light_shot \
    libarcsoft_mf_superresolution \
    libarcsoft_motiondetection \
    libarcsoft_night_hawk \
    libarcsoft_object_tracking \
    libarcsoft_rer \
    libarcsoft_smart_denoise \
    libarcsoft_super_night_raw \
    libarcsoft_superportrait \
    libarcsoft_video_hdr \
    libbitmlengine \
    libbitmlenginev2 \
    libc++_shared \
    libcamera_nn_stub \
    libcamerapostproc \
    libcammw_util \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcom.qti.chinodeutils \
    libets_teeclient_v2 \
    libface_landmark.arcsoft \
    libjpege \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmorpho_movie_stabilizer \
    libmorpho_single_camera \
    libmpbase \
    libofflinedump \
    libofflinelog \
    libopencv \
    libopestriping \
    libree_bix_agent \
    libsomc_camerapal \
    libsomc_chokoballcmn \
    libsomc_chokoballkeymgr \
    libsomc_chokoballpal \
    libsomc_thermal \
    libsomc_yummy \
    libsomc_yummyrsc \
    libsony_naruto \
    libtfestriping \
    libtriplecam_optical_zoom_control \
    libtriplecam_video_optical_zoom \
    libtriplecam_zoomtranslator_imp \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.semc.hardware.fingerprint-V1-ndk_platform

PRODUCT_PACKAGES += \
    vendor_firmware_bdwlan_bin
